### ISSUE TITLE
v1.1.1 fails to start

### ISSUE THREAD

**Issue by erain9** [ChihuahuaChain/mainnet#31]
I followed the README and version `v1.1.1` fails to start with the following error message

```
$ chihuahuad start
9:56PM INF starting ABCI with Tendermint
9:56PM INF Starting multiAppConn service impl=multiAppConn module=proxy
9:56PM INF Starting localClient service connection=query impl=localClient module=abci-client
9:56PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
9:56PM INF Starting localClient service connection=mempool impl=localClient module=abci-client
9:56PM INF Starting localClient service connection=consensus impl=localClient module=abci-client
9:56PM INF Starting EventBus service impl=EventBus module=events
9:56PM INF Starting PubSub service impl=PubSub module=pubsub
9:56PM INF Starting IndexerService service impl=IndexerService module=txindex
9:56PM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=v1.1.1
9:56PM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xf360f8]

goroutine 1 [running]:
math/big.(*Int).Sign(...)
        math/big/int.go:39
github.com/cosmos/cosmos-sdk/types.Dec.IsNegative(...)
        github.com/cosmos/cosmos-sdk@v0.44.5/types/decimal.go:203
github.com/cosmos/cosmos-sdk/x/staking/types.validateMinCommissionRate(0x19dd540, 0x0, 0x199, 0x19dd501)
        github.com/cosmos/cosmos-sdk@v0.44.5/x/staking/types/params.go:227 +0x38
github.com/cosmos/cosmos-sdk/x/params/types.Subspace.SetParamSet(0x1f56d38, 0x4000e8bd10, 0x4000129380, 0x1f25308, 0x400050f960, 0x1f25358, 0x400050fa10, 0x400014c348, 0x7, 0x18, ...)
        github.com/cosmos/cosmos-sdk@v0.44.5/x/params/types/subspace.go:236 +0x164
github.com/cosmos/cosmos-sdk/x/staking/keeper.Keeper.SetParams(...)
        github.com/cosmos/cosmos-sdk@v0.44.5/x/staking/keeper/params.go:70
github.com/cosmos/cosmos-sdk/x/staking.InitGenesis(0x1f41828, 0x4000124010, 0x1f598f8, 0x400015d980, 0x0, 0x0, 0x4000c881f0, 0xb, 0x0, 0x0, ...)
        github.com/cosmos/cosmos-sdk@v0.44.5/x/staking/genesis.go:35 +0x1e8
github.com/cosmos/cosmos-sdk/x/staking.AppModule.InitGenesis(0x1f5ca58, 0x4000e8bd10, 0x1f25308, 0x400050f8f0, 0x1f56d38, 0x4000e8bd10, 0x1f45b40, 0x40000e0480, 0xffff5c0ab298, 0x4000be31e0, ...)
        github.com/cosmos/cosmos-sdk@v0.44.5/x/staking/module.go:153 +0xec
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(0x4000bf0150, 0x1f41828, 0x4000124010, 0x1f598f8, 0x400015d980, 0x0, 0x0, 0x4000c881f0, 0xb, 0x0, ...)
        github.com/cosmos/cosmos-sdk@v0.44.5/types/module/module.go:307 +0x1f8
github.com/ChihuahuaChain/chihuahua/app.(*App).InitChainer(0x40001a6000, 0x1f41828, 0x4000124010, 0x1f598f8, 0x400015d980, 0x0, 0x0, 0x4000c881f0, 0xb, 0x0, ...)
        github.com/ChihuahuaChain/chihuahua/app/app.go:482 +0x188
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0x4000bee680, 0x0, 0xed94a8194, 0x0, 0x4000c881f0, 0xb, 0x400003ca80, 0x2c38208, 0x0, 0x0, ...)
        github.com/cosmos/cosmos-sdk@v0.44.5/baseapp/abci.go:62 +0x22c
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0x400012bbc0, 0x0, 0xed94a8194, 0x0, 0x4000c881f0, 0xb, 0x400003ca80, 0x2c38208, 0x0, 0x0, ...)
        github.com/tendermint/tendermint@v0.34.15/abci/client/local_client.go:272 +0xe4
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0x4000d94d50, 0x0, 0xed94a8194, 0x0, 0x4000c881f0, 0xb, 0x400003ca80, 0x2c38208, 0x0, 0x0, ...)
        github.com/tendermint/tendermint@v0.34.15/proxy/app_conn.go:77 +0x58
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0x4005cadbd0, 0xb, 0x0, 0x1ed8b30, 0x8, 0x4000c881f0, 0xb, 0x1, 0x0, 0x0, ...)
        github.com/tendermint/tendermint@v0.34.15/consensus/replay.go:319 +0x4c0
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0x4005cadbd0, 0x1f5aac8, 0x40001b01a0, 0x1f4, 0x400131fb10)
        github.com/tendermint/tendermint@v0.34.15/consensus/replay.go:268 +0x38c
github.com/tendermint/tendermint/node.doHandshake(0x1f57668, 0x4000df5d00, 0xb, 0x0, 0x1ed8b30, 0x8, 0x4000c881f0, 0xb, 0x1, 0x0, ...)
        github.com/tendermint/tendermint@v0.34.15/node/node.go:325 +0x12c
github.com/tendermint/tendermint/node.NewNode(0x400107b2c0, 0x1f38e20, 0x40001b90e0, 0x4000dc3c20, 0x1f03ed8, 0x4000141830, 0x4000dc3cd0, 0x1d1a618, 0x4000dc3dc0, 0x1f42580, ...)
        github.com/tendermint/tendermint@v0.34.15/node/node.go:733 +0x166c
github.com/cosmos/cosmos-sdk/server.startInProcess(0x40010e69e0, 0x0, 0x0, 0x0, 0x1f638b8, 0x4001145ad0, 0x0, 0x0, 0x1f4b0d0, 0x4000e8bd10, ...)
        github.com/cosmos/cosmos-sdk@v0.44.5/server/start.go:263 +0x4b8
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0x40010bb680, 0x2c38208, 0x0, 0x0, 0x0, 0x0)
        github.com/cosmos/cosmos-sdk@v0.44.5/server/start.go:129 +0x160
github.com/spf13/cobra.(*Command).execute(0x40010bb680, 0x2c38208, 0x0, 0x0, 0x40010bb680, 0x2c38208)
        github.com/spf13/cobra@v1.2.1/command.go:856 +0x320
github.com/spf13/cobra.(*Command).ExecuteC(0x4000e2a780, 0x0, 0x0, 0x4000043db8)
        github.com/spf13/cobra@v1.2.1/command.go:974 +0x274
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.2.1/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.2.1/command.go:895
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x4000e2a780, 0x4000043db8, 0x17, 0x9, 0x4000043db8)
        github.com/cosmos/cosmos-sdk@v0.44.5/server/cmd/execute.go:36 +0x22c
main.main()
        github.com/ChihuahuaChain/chihuahua/cmd/chihuahuad/main.go:21 +0xb4
```

Things are working fine once I switch to `v1.0.0`

**Comment by ChihuahuaChain** [comment]
If you are syncing the node from the genesis (without snapshot) as it seems looking at your your log, you need to start with 1.0.0 then update to 1.1.1 when required.

Alternatively, you can download snapshot and start from there with 1.1.1

**Comment by alanwilhelm** [comment]
Download the snapshot from where?
